### ISSUE TITLE
'AutoencoderKL' object has no attribute 'add_adapter'

### ISSUE THREAD

**Issue by YingJGuo** [GaParmar/img2img-turbo#64]
The AutoencoderKL has no attribute 'add_adapter' in diffusers 0.30 and 0.29.2.
It works in diffusers==0.25.1. 
But I'm curious about why the latest version removed this attribute, and whether there will be anything wrong with using add_adapter to finetune the vae.

I am new to this field, sry if the question is stupid.

**Comment by BeyondHeaven** [comment]
Thanks for your comment! I have the same issue and find the solution from you.

**Comment by HkDzl** [comment]
I am also curious
